{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cppdbg",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceFolder}/out/build/default/tests/grokking-tests",
            "args": [],
            "cwd": "${fileDirname}",
            "externalConsole": false,
            "MIMode": "lldb",
            "preLaunchTask": "CMake: build"
        }
    ]
}